apiVersion: v1
kind: Service
metadata:
  name: appservice
spec:
  selector:
    app: vproapp
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: vproport
      nodePort: 30007