apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprodb
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      containers:
      - name: vprodb
        image: vprofile/vprofiledb:V1
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: vprodbdata
        env:
         - name: MYSQL_ROOT_PASSWORD
           valueFrom:
             secretKeyRef:
               name: app-secret
               key: db-pass
        ports:
          - name: vprodbport
            containerPort: 3306       
      volumes:
        - name: vprodbdata
          hostPath:
            path: /data
            type: DirectoryOrCreate